RDKBACCL-527 : Need to check the populate_sdk_ext build in BPI Platform
Reason for change : Fixed below ESDK errors,
1. ERROR: nativesdk-python3-jinja2-2.11.1-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://files.pythonhosted.org/packages/source/j/jinja2/jinja2-2.11.1.tar.gz')
2. rdk-generic-broadband-image-1.0-r0 do_sdk_depends: The file /lib/systemd/system/usb-mount@.service is installed by both systemd and init-filogic, aborting
3. failed with exit code '1'ERROR: init-filogic-1.0-r0 do_package: Didn't find service unit 'usb-mount@.service', specified in SYSTEMD_SERVICE:init-filogic. Also looked for service unit 'usb-mount@.service'.
4. ERROR: rdk-generic-broadband-image-1.0-r0 do_populate_sdk_ext: Connecting to PR service localhost:0 failed: 'NoneType' object has no attribute 'port'
5. rdk_sdk/layers/meta-cmf/recipes-core/images/rdk-ipstb-oss-image.bb:9: Could not include required file ${RDKROOT}/meta-rdk/recipes-core/images/sdk-common.inc
Test Procedure: Tested the esdk script devtool
Risks: Low

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>